### ISSUE TITLE
Awsome notepad! Thanks. I wonder how to deply this app as a docker container?

### ISSUE THREAD

**Issue by robustmaster** [pereorga/minimalist-web-notepad#70]

**Comment by pereorga** [comment]
This is a really simple PHP application, which makes it straightforward to containerize with Docker (if that's really what you want). It is also straightforward to deploy it *without* Docker. I don't plan to commit a Dockerfile to the repo, or a docker-compose file, as personally I don't see the point). You may find examples in the issue queue if you use the GitHub search function, but you may also find a good tutorial on Google

**Comment by callumgare** [comment]
For me personally I really won't want to host PHP directly on my server for a variety for reasons (additional maintenance, security concerns, inconsistency with how I host everything else I run, etc) so to anyone else who's using docker this is the compose file I'm using (I use traefik with a shared network created by my traefik stack so you'll likely have to modify that part if you use a different reverse proxy setup):

```yaml
services:
  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - site-data:/usr/share/nginx/html
      - nginx-sites:/etc/nginx/conf.d
    labels:
      traefik.http.routers.notepad.rule: Host(`notepad.my.domain`)
    networks:
      - traefik_bus
      - default

  php:
    image: php:fpm
    restart: unless-stopped
    labels:
      traefik.enable: false
    volumes:
      - site-data:/usr/share/nginx/html

networks:
  traefik_bus:
    external: true
    
volumes:
  site-data:
  nginx-sites:
```

And this is the nginx config I'm using in a file called `default.conf` in my nginx-sites volume:
```nginx
server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    root   /usr/share/nginx/html;
    index  index.html index.htm index.php;
    try_files $uri $uri/ /index.php?$args;

    rewrite_log on;
    location ~ ^/([a-zA-Z0-9_-]+)$ {
        rewrite ^/([a-zA-Z0-9_-]+)$ /index.php?note=$1;
    }

    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param REQUEST_URI $request_uri;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
```

(@pereorga I hope this doesn't come across as ungrateful, I've been using this app for year and very much aperciate your work on it!)
